from summaries import summaries

class inferences:
    def __init__(self, documents):
        self.summarizer = summaries(documents)
    
    def get_documents(self):
        return self.summarizer.get_documents()
    
    def summarize(self, top_k=5, diversity=0.7, textrank_k=20):
        return self.summarizer.summarize(top_k=top_k, diversity=diversity, textrank_k=textrank_k)
    

if __name__ == "__main__":
    doc = """
Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh trên cơ sở vạch ra được các quy luật vận động, phát triển của xã hội loài người giúp chúng ta lựa chọn đúng đắn con đường phát triển của dân tộc - độc lập dân tộc gắn liền với chủ nghĩa xã hội. Lần đầu tiên trong lịch sử nhân loại, chủ nghĩa Mác - Lênin đã giải thích được quy luật phát triển của xã hội loài người một cách khoa học, khách quan, toàn diện, lịch sử - cụ thể. Chủ nghĩa Mác - Lênin đã chứng minh một cách khoa học rằng, từ trong lòng của chủ nghĩa tư bản sẽ ra đời phương thức sản xuất mới, một xã hội mới, một hình thái kinh tế - xã hội mới là chủ nghĩa xã hội, chủ nghĩa cộng sản. Quá trình này diễn ra một cách lịch sử - tự nhiên. Do vậy, sự ra đời cũng như diệt vong của chủ nghĩa tư bản là một tất yếu khách quan như nhau và đều do tất yếu kinh tế quy định. Cùng với chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh đã chỉ ra cho Đảng ta, dân tộc ta: “Độc lập dân tộc gắn liền với chủ nghĩa xã hội” - là sự lựa chọn đúng đắn con đường phát triển của Việt Nam. Bởi lẽ, độc lập dân tộc là cơ sở, điều kiện, tiền đề cho chủ nghĩa xã hội, còn chủ nghĩa xã hội mới bảo đảm cho độc lập dân tộc thực sự trọn vẹn, bền vững.

Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh với việc nhận thức chủ nghĩa tư bản hiện đại. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh với thế giới quan duy vật biện chứng và phương pháp luận biện chứng duy vật chỉ ra rằng, chủ nghĩa tư bản nhất định bị thay thế bởi chủ nghĩa xã hội. Chính chủ nghĩa tư bản tạo ra những điều kiện, tiền đề cho chủ nghĩa xã hội ra đời. Mặc dù hiện nay, chủ nghĩa tư bản đã đạt được những thành tựu nhất định về một số lĩnh vực: kinh tế, khoa học, công nghệ... Nhưng chính chủ nghĩa tư bản cũng là kẻ đã gây ra không ít tai họa cho con người như chiến tranh, nghèo đói, bất công xã hội, sự nô dịch áp bức... Những mục tiêu phục vụ con người, về hình thức và so với trước đây, có vẻ được quan tâm, nhưng thực chất ngày càng bị xa rời. Tiền lương thực tế của phần lớn công nhân Mỹ hầu như không tăng trong nhiều thập kỷ[29]. Chủ nghĩa tư bản về bản chất không thể giải quyết được vấn đề công bằng xã hội nhất là trong lĩnh vực phân phối nguồn của cải xã hội. Xu hướng giàu nghèo và phân tầng xã hội ngày càng diễn ra trầm trọng. Về bản chất, chủ nghĩa tư bản không tương thích với dân chủ[30]. Đúng như Đảng ta đã nhận định: “Hiện tại, chủ nghĩa tư bản còn tiềm năng phát triển, nhưng về bản chất vẫn là một chế độ áp bức, bóc lột và bất công. Những mâu thuẫn cơ bản vốn có của chủ nghĩa tư bản, nhất là mâu thuẫn giữa tính chất xã hội hóa ngày càng cao của lực lượng sản xuất với chế độ chiếm hữu tư nhân tư bản chủ nghĩa, chẳng những không được giải quyết mà ngày càng trở nên sâu sắc. Khủng hoảng kinh tế, chính trị, xã hội vẫn tiếp tục xảy ra”[31]. Đây là một yếu tố quan trọng góp phần đẩy nhanh chủ nghĩa tư bản đến giới hạn cuối cùng của nó. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh cũng chỉ ra rằng quá trình toàn cầu hóa kinh tế cũng là quá trình làm cho mâu thuẫn giữa tính chất xã hội hóa của lực lượng sản xuất với tính chất tư nhân tư bản chủ nghĩa mang tính toàn cầu. Quá trình này nhất định sẽ làm sâu sắc hơn mâu thuẫn cơ bản nội tại của chủ nghĩa tư bản, đẩy nhanh chủ nghĩa tư bản đến giới hạn cuối cùng của nó.

Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh với việc giải quyết quan hệ giữa tính phổ biến và tính đặc thù đi lên chủ nghĩa xã hội. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh cho chúng ta phương pháp nhận thức khoa học, đúng đắn con đường đi lên chủ nghĩa xã hội là mang tính phổ biến. Nhưng, mỗi dân tộc, quốc gia căn cứ vào tình hình thực tiễn của dân tộc, quốc gia mình mà lựa chọn hình thức quá độ trực tiếp hay gián tiếp lên chủ nghĩa xã hội. Đó là tính đặc thù và quan trọng là, không được vận dụng giáo điều những nguyên lý lý luận của chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh. Đồng thời phải chống việc tuyệt đối hóa những điều kiện cụ thể của dân tộc, quốc gia và hạ thấp những nguyên lý chung của chủ nghĩa Mác - Lênin, của chủ nghĩa xã hội. Bởi lẽ, khi ấy sẽ rơi vào dân tộc cực đoan, xét lại.

Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh với công cuộc đổi mới ở Việt Nam hiện nay. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh cho chúng ta phương pháp nhận thức điều kiện cụ thể để thực hiện công cuộc đổi mới ở Việt Nam hiện nay. Dựa trên nền tảng chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh, Đảng và Nhà nước ta có cơ sở lý luận để thực hiện đổi mới kinh tế - xã hội là trọng tâm, xây dựng Đảng là then chốt, xây dựng văn hóa, con người làm nền tảng tinh thần; tăng cường quốc phòng, an ninh là trọng yếu, thường xuyên[32]. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh còn cung cấp cho chúng ta cơ sở lý luận để tổng kết rút kinh nghiệm xây dựng chủ nghĩa xã hội trước đây, trên cơ sở đó đưa ra được tám đặc trưng bản chất của chủ nghĩa xã hội; tám phương hướng xây dựng chủ nghĩa xã hội và chín mối quan hệ lớn cần giải quyết[33]. Chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh cũng cung cấp cho chúng ta phương pháp luận để giải quyết tốt quan hệ giữa tăng trưởng kinh tế với thực hiện tiến bộ và công bằng xã hội; phát triển kinh tế thị trường với giữ vững định hướng xã hội chủ nghĩa; giữa xây dựng nền kinh tế độc lập, tự chủ với chủ động hội nhập quốc tế... Nói tóm lại, chính chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh là thế giới quan, phương pháp luận cho chúng ta thực hiện công cuộc đổi mới thành công.

Tất cả những điểm trên cho thấy, tại sao Đảng ta lại lấy chủ nghĩa Mác - Lênin, tư tưởng Hồ Chí Minh là nền tảng thế giới quan, kim chỉ nam cho hành động cách mạng."""
inf = inferences(doc)
summary = inf.summarize(top_k=5, diversity=0.7, textrank_k=20)
print("Tóm tắt:", summary)